// ─── 8-Language Localization System ──────────────────────────────────────────

export type Language =
  | "en" // English
  | "hi" // Hindi (हिंदी)
  | "es" // Spanish (Español)
  | "pt" // Portuguese (Português)
  | "fr" // French (Français)
  | "de" // German (Deutsch)
  | "id" // Indonesian (Bahasa Indonesia)
  | "ja"; // Japanese (日本語)

export interface LanguageInfo {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  { code: "en", name: "English", nativeName: "English", flag: "🇺🇸" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇧🇷" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia", flag: "🇮🇩" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
];

const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    game_title: "Water Sort",
    game_subtitle: "Premium Liquid Puzzle",
    play: "PLAY",
    continue: "CONTINUE",
    level: "Level",
    levels: "Levels",
    home: "Home",
    challenges: "Challenges",
    collection: "Collection",
    profile: "Profile",
    settings: "Settings",
    leaderboard: "Leaderboard",
    stats: "Stats",
    shop: "Store",
    premium: "Premium",
    moves: "Moves",
    par: "Par",
    time: "Time",
    undo: "Undo",
    hint: "Hint",
    restart: "Restart",
    skip: "Skip",
    pause: "Pause",
    resume: "Resume",
    restart_confirm: "Restart this level?",
    level_complete: "LEVEL COMPLETE!",
    next_level: "NEXT LEVEL",
    replay: "REPLAY",
    perfect: "PERFECT!",
    tubes_sorted: "Tubes Sorted",
    total_tubes_sorted: "Total Tubes Sorted",
    levels_completed: "Levels Completed",
    daily_challenge: "Daily Challenge",
    daily_streak: "Daily Streak",
    streak_days: "{n} Day Streak",
    claim_reward: "CLAIM REWARD",
    rank: "Rank",
    your_rank: "YOUR RANK",
    best_rank: "NEW BEST RANK!",
    global: "Global",
    weekly: "Weekly",
    all_time: "All Time",
    top_players: "Top Players",
    sound_fx: "Sound Effects",
    bg_music: "Background Music",
    haptics: "Haptic Vibration",
    dark_mode: "Dark Mode",
    language: "Language",
    background: "Background",
    theme: "Theme",
    colorblind_mode: "Colorblind Mode",
    colorblind_desc: "Displays patterns and symbols on liquids",
    high_contrast: "High Contrast",
    accessibility: "Accessibility",
    remove_ads: "Remove Ads",
    restore_purchases: "Restore Purchases",
    unlimited_hints: "Unlimited Hints",
    unlimited_undos: "Unlimited Undos",
    all_themes_unlocked: "All Themes & Backgrounds",
    vip_badge: "VIP Master Badge",
    guest_player: "Guest Player",
    edit_profile: "Edit Profile",
    player_name: "Player Name",
    save: "Save",
    cancel: "Cancel",
    watch_ad_hint: "Watch Ad for Hint",
    watch_ad_skip: "Watch Ad to Skip",
    ad_unavailable: "Ad temporarily unavailable. Please try again soon.",
    offline_mode: "Offline Mode Active",
    locked: "Locked",
    unlocked: "Unlocked",
    equipped: "Equipped",
    use_this: "Use This",
    milestone_level: "MILESTONE LEVEL",
    celebration_badge: "Milestone Badge Unlocked!",
    achievements: "Achievements",
    difficulty_tutorial: "Tutorial",
    difficulty_easy: "Easy",
    difficulty_medium: "Medium",
    difficulty_hard: "Hard",
    difficulty_veryhard: "Very Hard",
    difficulty_expert: "Expert",
    difficulty_master: "Master",
    chapter: "Chapter",
    jump_to_current: "Jump to Current",
    challenge_limited_moves: "Limited Moves",
    challenge_time_attack: "Time Attack",
    challenge_hard_puzzle: "Hard Puzzle",
    challenge_no_hint: "No Hints Allowed",
    challenge_expert: "Expert Challenge",
    challenge_special_tube: "Flask Master",
    about_game: "A soothing premium puzzle experience crafted for minds that appreciate beauty and logic.",
  },
  hi: {
    game_title: "वॉटर सॉर्ट",
    game_subtitle: "प्रीमियम लिक्विड पहेली",
    play: "खेलें",
    continue: "जारी रखें",
    level: "स्तर",
    levels: "स्तरें",
    home: "होम",
    challenges: "चुनौतियां",
    collection: "संग्रह",
    profile: "प्रोफ़ाइल",
    settings: "सेटिंग्स",
    leaderboard: "लीडरबोर्ड",
    stats: "आंकड़े",
    shop: "दुकान",
    premium: "प्रीमियम",
    moves: "चालें",
    par: "पार",
    time: "समय",
    undo: "वापस लें",
    hint: "संकेत",
    restart: "पुनः आरंभ",
    skip: "छोड़ें",
    pause: "रोकें",
    resume: "जारी रखें",
    restart_confirm: "क्या आप इस स्तर को पुनः आरंभ करना चाहते हैं?",
    level_complete: "स्तर पूर्ण!",
    next_level: "अगला स्तर",
    replay: "पुनः खेलें",
    perfect: "उत्कृष्ट!",
    tubes_sorted: "सॉर्ट की गई ट्यूब्स",
    total_tubes_sorted: "कुल सॉर्ट की गई ट्यूब्स",
    levels_completed: "पूर्ण किए गए स्तर",
    daily_challenge: "दैनिक चुनौती",
    daily_streak: "दैनिक स्ट्रीक",
    streak_days: "{n} दिन की स्ट्रीक",
    claim_reward: "इनाम प्राप्त करें",
    rank: "रैंक",
    your_rank: "आपकी रैंक",
    best_rank: "नई सर्वश्रेष्ठ रैंक!",
    global: "ग्लोबल",
    weekly: "साप्ताहिक",
    all_time: "सर्वकालिक",
    top_players: "शीर्ष खिलाड़ी",
    sound_fx: "ध्वनि प्रभाव",
    bg_music: "पृष्ठभूमि संगीत",
    haptics: "कंपन फीडबैक",
    dark_mode: "डार्क मोड",
    language: "भाषा",
    background: "पृष्ठभूमि",
    theme: "थीम",
    colorblind_mode: "कलरब्लाइंड मोड",
    colorblind_desc: "तरल पदार्थों पर प्रतीक दिखाता है",
    high_contrast: "उच्च कंट्रास्ट",
    accessibility: "सुलभता",
    remove_ads: "विज्ञापन हटाएं",
    restore_purchases: "खरीदारी पुनर्स्थापित करें",
    unlimited_hints: "असीमित संकेत",
    unlimited_undos: "असीमित अनडू",
    all_themes_unlocked: "सभी थीम्स और बैकग्राउंड",
    vip_badge: "वीआईपी मास्टर बैज",
    guest_player: "अतिथि खिलाड़ी",
    edit_profile: "प्रोफ़ाइल संपादित करें",
    player_name: "खिलाड़ी का नाम",
    save: "सहेजें",
    cancel: "रद्द करें",
    watch_ad_hint: "संकेत के लिए विज्ञापन देखें",
    watch_ad_skip: "छोड़ने के लिए विज्ञापन देखें",
    ad_unavailable: "विज्ञापन अस्थायी रूप से अनुपलब्ध है।",
    offline_mode: "ऑफ़लाइन मोड सक्रिय",
    locked: "बंद",
    unlocked: "खुला",
    equipped: "सक्रिय",
    use_this: "उपयोग करें",
    milestone_level: "माइलस्टोन स्तर",
    celebration_badge: "माइलस्टोन बैज खुला!",
    achievements: "उपलब्धियां",
    difficulty_tutorial: "ट्यूटोरियल",
    difficulty_easy: "आसान",
    difficulty_medium: "मध्यम",
    difficulty_hard: "कठिन",
    difficulty_veryhard: "अति कठिन",
    difficulty_expert: "विशेषज्ञ",
    difficulty_master: "मास्टर",
    chapter: "अध्याय",
    jump_to_current: "वर्तमान पर जाएं",
    challenge_limited_moves: "सीमित चालें",
    challenge_time_attack: "समय सीमा",
    challenge_hard_puzzle: "कठिन पहेली",
    challenge_no_hint: "बिना संकेत",
    challenge_expert: "विशेषज्ञ चुनौती",
    challenge_special_tube: "फ्लास्क मास्टर",
    about_game: "सुंदरता और तर्क की सराहना करने वालों के लिए एक शांत पहेली अनुभव।",
  },
  es: {
    game_title: "Water Sort",
    game_subtitle: "Puzle Líquido Premium",
    play: "JUGAR",
    continue: "CONTINUAR",
    level: "Nivel",
    levels: "Niveles",
    home: "Inicio",
    challenges: "Desafíos",
    collection: "Colección",
    profile: "Perfil",
    settings: "Ajustes",
    leaderboard: "Clasificación",
    stats: "Estadísticas",
    shop: "Tienda",
    premium: "Premium",
    moves: "Movimientos",
    par: "Par",
    time: "Tiempo",
    undo: "Deshacer",
    hint: "Pista",
    restart: "Reiniciar",
    skip: "Saltar",
    pause: "Pausa",
    resume: "Reanudar",
    restart_confirm: "¿Reiniciar este nivel?",
    level_complete: "¡NIVEL COMPLETADO!",
    next_level: "SIGUIENTE NIVEL",
    replay: "REPETIR",
    perfect: "¡PERFECTO!",
    tubes_sorted: "Tubos Ordenados",
    total_tubes_sorted: "Tubos Totales Ordenados",
    levels_completed: "Niveles Completados",
    daily_challenge: "Desafío Diario",
    daily_streak: "Racha Diaria",
    streak_days: "Racha de {n} días",
    claim_reward: "RECLAMAR RECOMPENSA",
    rank: "Rango",
    your_rank: "TU RANGO",
    best_rank: "¡NUEVO MEJOR RANGO!",
    global: "Global",
    weekly: "Semanal",
    all_time: "Histórico",
    top_players: "Mejores Jugadores",
    sound_fx: "Efectos de Sonido",
    bg_music: "Música de Fondo",
    haptics: "Vibración Háptica",
    dark_mode: "Modo Oscuro",
    language: "Idioma",
    background: "Fondo",
    theme: "Tema",
    colorblind_mode: "Modo Daltónico",
    colorblind_desc: "Muestra patrones y símbolos en los líquidos",
    high_contrast: "Alto Contraste",
    accessibility: "Accesibilidad",
    remove_ads: "Eliminar Anuncios",
    restore_purchases: "Restaurar Compras",
    unlimited_hints: "Pistas Ilimitadas",
    unlimited_undos: "Deshacer Ilimitado",
    all_themes_unlocked: "Todos los Temas y Fondos",
    vip_badge: "Insignia VIP Master",
    guest_player: "Jugador Invitado",
    edit_profile: "Editar Perfil",
    player_name: "Nombre de Jugador",
    save: "Guardar",
    cancel: "Cancelar",
    watch_ad_hint: "Ver Anuncio por Pista",
    watch_ad_skip: "Ver Anuncio para Saltar",
    ad_unavailable: "Anuncio no disponible en este momento.",
    offline_mode: "Modo Sin Conexión",
    locked: "Bloqueado",
    unlocked: "Desbloqueado",
    equipped: "Equipado",
    use_this: "Usar Este",
    milestone_level: "NIVEL HITO",
    celebration_badge: "¡Insignia de Hito Desbloqueada!",
    achievements: "Logros",
    difficulty_tutorial: "Tutorial",
    difficulty_easy: "Fácil",
    difficulty_medium: "Medio",
    difficulty_hard: "Difícil",
    difficulty_veryhard: "Muy Difícil",
    difficulty_expert: "Experto",
    difficulty_master: "Maestro",
    chapter: "Capítulo",
    jump_to_current: "Ir al Actual",
    challenge_limited_moves: "Movimientos Limitados",
    challenge_time_attack: "Contrarreloj",
    challenge_hard_puzzle: "Puzle Difícil",
    challenge_no_hint: "Sin Pistas",
    challenge_expert: "Desafío Experto",
    challenge_special_tube: "Maestro del Matraz",
    about_game: "Una experiencia relajante diseñada para mentes lógicas.",
  },
  pt: {
    game_title: "Water Sort",
    game_subtitle: "Quebra-Cabeça de Líquidos",
    play: "JOGAR",
    continue: "CONTINUAR",
    level: "Nível",
    levels: "Níveis",
    home: "Início",
    challenges: "Desafios",
    collection: "Coleção",
    profile: "Perfil",
    settings: "Configurações",
    leaderboard: "Classificação",
    stats: "Estatísticas",
    shop: "Loja",
    premium: "Premium",
    moves: "Movimentos",
    par: "Par",
    time: "Tempo",
    undo: "Desfazer",
    hint: "Dica",
    restart: "Reiniciar",
    skip: "Pular",
    pause: "Pausar",
    resume: "Retomar",
    restart_confirm: "Reiniciar este nível?",
    level_complete: "NÍVEL CONCLUÍDO!",
    next_level: "PRÓXIMO NÍVEL",
    replay: "JOGAR DE NOVO",
    perfect: "PERFEITO!",
    tubes_sorted: "Tubos Organizados",
    total_tubes_sorted: "Total de Tubos Organizados",
    levels_completed: "Níveis Concluídos",
    daily_challenge: "Desafio Diário",
    daily_streak: "Sequência Diária",
    streak_days: "Sequência de {n} dias",
    claim_reward: "RESGATAR RECOMPENSA",
    rank: "Classificação",
    your_rank: "SUA CLASSIFICAÇÃO",
    best_rank: "NOVA MELHOR CLASSIFICAÇÃO!",
    global: "Global",
    weekly: "Semanal",
    all_time: "Geral",
    top_players: "Melhores Jogadores",
    sound_fx: "Efeitos Sonoros",
    bg_music: "Música de Fundo",
    haptics: "Vibração Tátil",
    dark_mode: "Modo Escuro",
    language: "Idioma",
    background: "Fundo",
    theme: "Tema",
    colorblind_mode: "Modo Daltônico",
    colorblind_desc: "Exibe símbolos e padrões nos líquidos",
    high_contrast: "Alto Contraste",
    accessibility: "Acessibilidade",
    remove_ads: "Remover Anúncios",
    restore_purchases: "Restaurar Compras",
    unlimited_hints: "Dicas Ilimitadas",
    unlimited_undos: "Desfazer Ilimitado",
    all_themes_unlocked: "Todos os Temas e Fundos",
    vip_badge: "Distintivo VIP Master",
    guest_player: "Jogador Convidado",
    edit_profile: "Editar Perfil",
    player_name: "Nome do Jogador",
    save: "Salvar",
    cancel: "Cancelar",
    watch_ad_hint: "Assistir Anúncio por Dica",
    watch_ad_skip: "Assistir Anúncio para Pular",
    ad_unavailable: "Anúncio indisponível no momento.",
    offline_mode: "Modo Offline Ativo",
    locked: "Bloqueado",
    unlocked: "Desbloqueado",
    equipped: "Equipado",
    use_this: "Usar Este",
    milestone_level: "NÍVEL MARCO",
    celebration_badge: "Distintivo Marco Desbloqueado!",
    achievements: "Conquistas",
    difficulty_tutorial: "Tutorial",
    difficulty_easy: "Fácil",
    difficulty_medium: "Médio",
    difficulty_hard: "Difícil",
    difficulty_veryhard: "Muito Difícil",
    difficulty_expert: "Especialista",
    difficulty_master: "Mestre",
    chapter: "Capítulo",
    jump_to_current: "Ir para o Atual",
    challenge_limited_moves: "Movimentos Limitados",
    challenge_time_attack: "Contra o Relógio",
    challenge_hard_puzzle: "Quebra-Cabeça Difícil",
    challenge_no_hint: "Sem Dicas",
    challenge_expert: "Desafio Especialista",
    challenge_special_tube: "Mestre do Frasco",
    about_game: "Uma experiência relaxante projetada para mentes lógicas.",
  },
  fr: {
    game_title: "Water Sort",
    game_subtitle: "Casse-Tête Liquide Premium",
    play: "JOUER",
    continue: "CONTINUER",
    level: "Niveau",
    levels: "Niveaux",
    home: "Accueil",
    challenges: "Défis",
    collection: "Collection",
    profile: "Profil",
    settings: "Paramètres",
    leaderboard: "Classement",
    stats: "Statistiques",
    shop: "Boutique",
    premium: "Premium",
    moves: "Coups",
    par: "Par",
    time: "Temps",
    undo: "Annuler",
    hint: "Indice",
    restart: "Recommencer",
    skip: "Passer",
    pause: "Pause",
    resume: "Reprendre",
    restart_confirm: "Recommencer ce niveau ?",
    level_complete: "NIVEAU TERMINÉ !",
    next_level: "NIVEAU SUIVANT",
    replay: "REJOUER",
    perfect: "PARFAIT !",
    tubes_sorted: "Tubes Triés",
    total_tubes_sorted: "Total Tubes Triés",
    levels_completed: "Niveaux Terminés",
    daily_challenge: "Défi Quotidien",
    daily_streak: "Série Quotidienne",
    streak_days: "Série de {n} jours",
    claim_reward: "RÉCUPÉRER RÉCOMPENSE",
    rank: "Rang",
    your_rank: "VOTRE RANG",
    best_rank: "NOUVEAU MEILLEUR RANG !",
    global: "Mondial",
    weekly: "Hebdomadaire",
    all_time: "Général",
    top_players: "Meilleurs Joueurs",
    sound_fx: "Effets Sonores",
    bg_music: "Musique d'Ambiance",
    haptics: "Retour Tactile",
    dark_mode: "Mode Sombre",
    language: "Langue",
    background: "Arrière-Plan",
    theme: "Thème",
    colorblind_mode: "Mode Daltonien",
    colorblind_desc: "Affiche des symboles sur les liquides",
    high_contrast: "Contraste Élevé",
    accessibility: "Accessibilité",
    remove_ads: "Supprimer les Publicités",
    restore_purchases: "Restaurer Achats",
    unlimited_hints: "Indices Illimités",
    unlimited_undos: "Annulations Illimitées",
    all_themes_unlocked: "Tous les Thèmes et Décors",
    vip_badge: "Badge Maître VIP",
    guest_player: "Joueur Invité",
    edit_profile: "Modifier Profil",
    player_name: "Nom du Joueur",
    save: "Enregistrer",
    cancel: "Annuler",
    watch_ad_hint: "Regarder une Pub pour un Indice",
    watch_ad_skip: "Regarder une Pub pour Passer",
    ad_unavailable: "Publicité indisponible pour l'instant.",
    offline_mode: "Mode Hors-Ligne Actif",
    locked: "Verrouillé",
    unlocked: "Débloqué",
    equipped: "Équipé",
    use_this: "Utiliser",
    milestone_level: "NIVEAU PALIER",
    celebration_badge: "Badge Palier Débloqué !",
    achievements: "Succès",
    difficulty_tutorial: "Tutoriel",
    difficulty_easy: "Facile",
    difficulty_medium: "Moyen",
    difficulty_hard: "Difficile",
    difficulty_veryhard: "Très Difficile",
    difficulty_expert: "Expert",
    difficulty_master: "Maître",
    chapter: "Chapitre",
    jump_to_current: "Aller au Niveau Actuel",
    challenge_limited_moves: "Coups Limités",
    challenge_time_attack: "Contre la Montre",
    challenge_hard_puzzle: "Casse-Tête Difficile",
    challenge_no_hint: "Sans Indice",
    challenge_expert: "Défi Expert",
    challenge_special_tube: "Maître de la Fiole",
    about_game: "Une expérience apaisante conçue pour les esprits logiques.",
  },
  de: {
    game_title: "Water Sort",
    game_subtitle: "Premium Flüssigkeitspuzzle",
    play: "SPIELEN",
    continue: "WEITER",
    level: "Level",
    levels: "Levels",
    home: "Start",
    challenges: "Herausforderungen",
    collection: "Sammlung",
    profile: "Profil",
    settings: "Einstellungen",
    leaderboard: "Bestenliste",
    stats: "Statistiken",
    shop: "Laden",
    premium: "Premium",
    moves: "Züge",
    par: "Par",
    time: "Zeit",
    undo: "Rückgängig",
    hint: "Hinweis",
    restart: "Neustart",
    skip: "Überspringen",
    pause: "Pause",
    resume: "Fortsetzen",
    restart_confirm: "Dieses Level neustarten?",
    level_complete: "LEVEL GESCHAFFT!",
    next_level: "NÄCHSTES LEVEL",
    replay: "WIEDERHOLEN",
    perfect: "PERFEKT!",
    tubes_sorted: "Sortierte Röhren",
    total_tubes_sorted: "Gesamte Sortierte Röhren",
    levels_completed: "Abgeschlossene Level",
    daily_challenge: "Tages-Rätsel",
    daily_streak: "Tägliche Serie",
    streak_days: "{n} Tage Serie",
    claim_reward: "BELOHNUNG ABHOLEN",
    rank: "Rang",
    your_rank: "DEIN RANG",
    best_rank: "NEUER BESTER RANG!",
    global: "Global",
    weekly: "Wöchentlich",
    all_time: "Gesamt",
    top_players: "Top-Spieler",
    sound_fx: "Soundeffekte",
    bg_music: "Hintergrundmusik",
    haptics: "Haptisches Feedback",
    dark_mode: "Dunkelmodus",
    language: "Sprache",
    background: "Hintergrund",
    theme: "Design",
    colorblind_mode: "Farbenblind-Modus",
    colorblind_desc: "Zeigt Symbole auf den Flüssigkeiten",
    high_contrast: "Hoher Kontrast",
    accessibility: "Barrierefreiheit",
    remove_ads: "Werbung entfernen",
    restore_purchases: "Käufe wiederherstellen",
    unlimited_hints: "Unbegrenzte Hinweise",
    unlimited_undos: "Unbegrenztes Rückgängig",
    all_themes_unlocked: "Alle Designs & Hintergründe",
    vip_badge: "VIP-Meister-Abzeichen",
    guest_player: "Gastspieler",
    edit_profile: "Profil bearbeiten",
    player_name: "Spielername",
    save: "Speichern",
    cancel: "Abbrechen",
    watch_ad_hint: "Werbung für Hinweis sehen",
    watch_ad_skip: "Werbung zum Überspringen sehen",
    ad_unavailable: "Werbung derzeit nicht verfügbar.",
    offline_mode: "Offline-Modus aktiv",
    locked: "Gesperrt",
    unlocked: "Freigeschaltet",
    equipped: "Ausgerüstet",
    use_this: "Verwenden",
    milestone_level: "MEILENSTEIN-LEVEL",
    celebration_badge: "Meilenstein-Abzeichen erhalten!",
    achievements: "Erfolge",
    difficulty_tutorial: "Tutorial",
    difficulty_easy: "Einfach",
    difficulty_medium: "Mittel",
    difficulty_hard: "Schwer",
    difficulty_veryhard: "Sehr Schwer",
    difficulty_expert: "Experte",
    difficulty_master: "Meister",
    chapter: "Kapitel",
    jump_to_current: "Zum aktuellen Level",
    challenge_limited_moves: "Begrenzte Züge",
    challenge_time_attack: "Gegen die Zeit",
    challenge_hard_puzzle: "Schweres Rätsel",
    challenge_no_hint: "Ohne Hinweise",
    challenge_expert: "Experten-Rätsel",
    challenge_special_tube: "Kolben-Meister",
    about_game: "Ein beruhigendes Puzzle-Erlebnis für scharfsinnige Köpfe.",
  },
  id: {
    game_title: "Water Sort",
    game_subtitle: "Teka-Teki Cairan Premium",
    play: "MAIN",
    continue: "LANJUTKAN",
    level: "Level",
    levels: "Level",
    home: "Beranda",
    challenges: "Tantangan",
    collection: "Koleksi",
    profile: "Profil",
    settings: "Pengaturan",
    leaderboard: "Papan Peringkat",
    stats: "Statistik",
    shop: "Toko",
    premium: "Premium",
    moves: "Langkah",
    par: "Par",
    time: "Waktu",
    undo: "Batal",
    hint: "Petunjuk",
    restart: "Ulangi",
    skip: "Lewati",
    pause: "Jeda",
    resume: "Lanjutkan",
    restart_confirm: "Ulangi level ini?",
    level_complete: "LEVEL SELESAI!",
    next_level: "LEVEL BERIKUTNYA",
    replay: "MAIN LAGI",
    perfect: "SEMPURNA!",
    tubes_sorted: "Tabung Tersortir",
    total_tubes_sorted: "Total Tabung Tersortir",
    levels_completed: "Level Diselesaikan",
    daily_challenge: "Tantangan Harian",
    daily_streak: "Rentetan Harian",
    streak_days: "Rentetan {n} Hari",
    claim_reward: "KLAIM HADIAH",
    rank: "Peringkat",
    your_rank: "PERINGKAT ANDA",
    best_rank: "PERINGKAT TERBAIK BARU!",
    global: "Global",
    weekly: "Mingguan",
    all_time: "Sepanjang Masa",
    top_players: "Pemain Teratas",
    sound_fx: "Efek Suara",
    bg_music: "Musik Latar",
    haptics: "Getaran Haptik",
    dark_mode: "Mode Gelap",
    language: "Bahasa",
    background: "Latar Belakang",
    theme: "Tema",
    colorblind_mode: "Mode Buta Warna",
    colorblind_desc: "Menampilkan simbol pada cairan",
    high_contrast: "Kontras Tinggi",
    accessibility: "Aksesibilitas",
    remove_ads: "Hapus Iklan",
    restore_purchases: "Pulihkan Pembelian",
    unlimited_hints: "Petunjuk Tak Terbatas",
    unlimited_undos: "Undo Tak Terbatas",
    all_themes_unlocked: "Semua Tema & Latar Belakang",
    vip_badge: "Lencana VIP Master",
    guest_player: "Pemain Tamu",
    edit_profile: "Edit Profil",
    player_name: "Nama Pemain",
    save: "Simpan",
    cancel: "Batal",
    watch_ad_hint: "Tonton Iklan untuk Petunjuk",
    watch_ad_skip: "Tonton Iklan untuk Lewati",
    ad_unavailable: "Iklan sedang tidak tersedia.",
    offline_mode: "Mode Offline Aktif",
    locked: "Terkunci",
    unlocked: "Terbuka",
    equipped: "Dipakai",
    use_this: "Gunakan Ini",
    milestone_level: "LEVEL TONGGAK",
    celebration_badge: "Lencana Tonggak Terbuka!",
    achievements: "Pencapaian",
    difficulty_tutorial: "Tutorial",
    difficulty_easy: "Mudah",
    difficulty_medium: "Sedang",
    difficulty_hard: "Sulit",
    difficulty_veryhard: "Sangat Sulit",
    difficulty_expert: "Pakar",
    difficulty_master: "Master",
    chapter: "Bab",
    jump_to_current: "Lompat ke Saat Ini",
    challenge_limited_moves: "Langkah Terbatas",
    challenge_time_attack: "Serangan Waktu",
    challenge_hard_puzzle: "Teka-Teki Sulit",
    challenge_no_hint: "Tanpa Petunjuk",
    challenge_expert: "Tantangan Pakar",
    challenge_special_tube: "Master Labu",
    about_game: "Pengalaman teka-teki menenangkan untuk pikiran yang cerdas.",
  },
  ja: {
    game_title: "ウォーターソート",
    game_subtitle: "プレミアム液体パズル",
    play: "プレイ",
    continue: "つづける",
    level: "レベル",
    levels: "レベル一覧",
    home: "ホーム",
    challenges: "チャレンジ",
    collection: "コレクション",
    profile: "プロフィール",
    settings: "設定",
    leaderboard: "ランキング",
    stats: "成績",
    shop: "ショップ",
    premium: "プレミアム",
    moves: "手数",
    par: "基準手",
    time: "時間",
    undo: "1手戻す",
    hint: "ヒント",
    restart: "やり直す",
    skip: "スキップ",
    pause: "一時停止",
    resume: "再開",
    restart_confirm: "このレベルをやり直しますか？",
    level_complete: "レベルクリア！",
    next_level: "次のレベル",
    replay: "もう一度",
    perfect: "パーフェクト！",
    tubes_sorted: "完成したチューブ",
    total_tubes_sorted: "総完成チューブ数",
    levels_completed: "クリアレベル数",
    daily_challenge: "デイリーチャレンジ",
    daily_streak: "デイリー連続",
    streak_days: "{n}日連続達成",
    claim_reward: "報酬を受け取る",
    rank: "順位",
    your_rank: "あなたの順位",
    best_rank: "自己最高順位更新！",
    global: "世界",
    weekly: "週間",
    all_time: "歴代",
    top_players: "トップランカー",
    sound_fx: "効果音",
    bg_music: "BGM",
    haptics: "振動フィードバック",
    dark_mode: "ダークモード",
    language: "言語",
    background: "背景",
    theme: "テーマ",
    colorblind_mode: "色覚サポート",
    colorblind_desc: "液体にパターンと記号を表示します",
    high_contrast: "ハイコントラスト",
    accessibility: "アクセシビリティ",
    remove_ads: "広告を非表示",
    restore_purchases: "購入の復元",
    unlimited_hints: "無制限のヒント",
    unlimited_undos: "無制限のやり直し",
    all_themes_unlocked: "全テーマ・背景アンロック",
    vip_badge: "VIPマスターバッジ",
    guest_player: "ゲストプレイヤー",
    edit_profile: "プロフィール編集",
    player_name: "プレイヤー名",
    save: "保存",
    cancel: "キャンセル",
    watch_ad_hint: "広告を見てヒント獲得",
    watch_ad_skip: "広告を見てスキップ",
    ad_unavailable: "現在広告を読み込めません。",
    offline_mode: "オフラインモード稼働中",
    locked: "ロック",
    unlocked: "解除済み",
    equipped: "装着中",
    use_this: "これを使う",
    milestone_level: "マイルストーンレベル",
    celebration_badge: "記念バッジを獲得しました！",
    achievements: "実績",
    difficulty_tutorial: "チュートリアル",
    difficulty_easy: "かんたん",
    difficulty_medium: "ふつう",
    difficulty_hard: "むずかしい",
    difficulty_veryhard: "激ムズ",
    difficulty_expert: "エキスパート",
    difficulty_master: "マスター",
    chapter: "チャプター",
    jump_to_current: "現在のレベルへ",
    challenge_limited_moves: "手数制限",
    challenge_time_attack: "タイムアタック",
    challenge_hard_puzzle: "高難度パズル",
    challenge_no_hint: "ヒントなし",
    challenge_expert: "達人チャレンジ",
    challenge_special_tube: "フラスコマスター",
    about_game: "論理と美しさを愛する人のための、心地よい上質パズル体験。",
  },
};

const KEY_LANG = "ws2_language";

let currentLang: Language = "en";
const listeners = new Set<(lang: Language) => void>();

export function getSavedLanguage(): Language {
  try {
    const saved = localStorage.getItem(KEY_LANG);
    if (saved && saved in TRANSLATIONS) return saved as Language;
    // Auto-detect browser language
    const navLang = navigator.language?.slice(0, 2).toLowerCase();
    if (navLang && navLang in TRANSLATIONS) return navLang as Language;
  } catch {
    // Ignore storage issues
  }
  return "en";
}

export function setLanguage(lang: Language): void {
  if (!(lang in TRANSLATIONS)) return;
  currentLang = lang;
  try {
    localStorage.setItem(KEY_LANG, lang);
  } catch {
    // Ignore
  }
  listeners.forEach((fn) => fn(lang));
}

export function getCurrentLanguage(): Language {
  return currentLang;
}

export function subscribeLanguage(fn: (lang: Language) => void): () => void {
  listeners.add(fn);
  return () => listeners.delete(fn);
}

// Translate key with optional parameter replacement
export function t(key: string, params?: Record<string, string | number>): string {
  let text = TRANSLATIONS[currentLang]?.[key] || TRANSLATIONS.en[key] || key;
  if (params) {
    Object.entries(params).forEach(([k, v]) => {
      text = text.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
    });
  }
  return text;
}

// Initialize on module load
currentLang = getSavedLanguage();
